use factor_engine::types::{CompileOptions, Universe};
use factor_engine::{
    AdvancePolicy, Engine, FactorRequest, InputFieldCatalog, OnlineFactorEngine, Planner,
    SimplePlanner,
};
use std::collections::{BTreeMap, HashMap};

mod common;
use common::alpha101::*;

#[test]
fn polars_offline_matches_online_alpha101_batch_a_missing_set() {
    if !python_polars_available() {
        eprintln!("skip: python3/polars unavailable");
        return;
    }

    let universe = vec![9101_u32, 9102, 9103, 9104, 9105, 9106];
    let ts_points: Vec<i64> = (1..=420).collect();
    let outputs = vec![
        "alpha001".to_string(),
        "alpha002".to_string(),
        "alpha005".to_string(),
        "alpha007".to_string(),
        "alpha008".to_string(),
        "alpha009".to_string(),
        "alpha010".to_string(),
        "alpha011".to_string(),
        "alpha014".to_string(),
        "alpha017".to_string(),
        "alpha019".to_string(),
    ];

    // Canonicalized alpha101 expressions using current engine naming.
    let expr_alpha001 = "cs_rank(ts_argmax(elem_signed_power(elem_where((ts_delta(close, 1) / (ts_lag(close, 1) + 0.000001)) < 0, ts_std((ts_delta(close, 1) / (ts_lag(close, 1) + 0.000001)), 20), close), 2), 5)) - 0.5";
    let expr_alpha002 =
        "-1 * ts_corr(cs_rank(ts_delta(elem_log(volume), 2)), cs_rank((close - open) / open), 6)";
    let expr_alpha005 = "-1 * elem_abs(cs_rank(close - ((open + high + low + close) / 4))) * cs_rank(open - ts_mean(((open + high + low + close) / 4), 10))";
    let expr_alpha007 = "elem_where(ts_mean(volume, 20) < volume, -1 * elem_sign(ts_delta(close, 7)) * ts_rank(elem_abs(ts_delta(close, 7)), 60), -1)";
    let expr_alpha008 = "-1 * cs_rank(ts_sum(open, 5) * ts_sum((ts_delta(close, 1) / (ts_lag(close, 1) + 0.000001)), 5) - ts_lag(ts_sum(open, 5) * ts_sum((ts_delta(close, 1) / (ts_lag(close, 1) + 0.000001)), 5), 10))";
    let expr_alpha009 = "elem_where(ts_min(ts_delta(close, 1), 5) > 0, ts_delta(close, 1), elem_where(ts_max(ts_delta(close, 1), 5) < 0, ts_delta(close, 1), -1 * ts_delta(close, 1)))";
    let expr_alpha010 = "cs_rank(elem_where(ts_min(ts_delta(close, 1), 4) > 0, ts_delta(close, 1), elem_where(ts_max(ts_delta(close, 1), 4) < 0, ts_delta(close, 1), -1 * ts_delta(close, 1))))";
    let expr_alpha011 = "(cs_rank(ts_max(-1 * (close - ((open + high + low + close) / 4)), 3)) + cs_rank(ts_min(-1 * (close - ((open + high + low + close) / 4)), 3))) * cs_rank(ts_delta(volume, 3))";
    let expr_alpha014 = "-1 * cs_rank(ts_delta((ts_delta(close, 1) / (ts_lag(close, 1) + 0.000001)), 3)) * ts_corr(open, volume, 10)";
    let expr_alpha017 = "-1 * cs_rank(ts_delta(ts_delta(close, 1), 1)) * cs_rank(ts_rank(close, 10)) * cs_rank(ts_rank(volume / ts_mean(volume, 20), 5))";
    let expr_alpha019 = "-1 * (cs_rank(ts_sum((ts_delta(close, 1) / (ts_lag(close, 1) + 0.000001)), 250) + 1) + 1) * elem_sign(close + ts_delta(close, 7) - ts_lag(close, 7))";

    let request = FactorRequest {
        exprs: vec![
            expr_alpha001.to_string(),
            expr_alpha002.to_string(),
            expr_alpha005.to_string(),
            expr_alpha007.to_string(),
            expr_alpha008.to_string(),
            expr_alpha009.to_string(),
            expr_alpha010.to_string(),
            expr_alpha011.to_string(),
            expr_alpha014.to_string(),
            expr_alpha017.to_string(),
            expr_alpha019.to_string(),
        ],
        outputs: outputs.clone(),
        opts: CompileOptions::default(),
    };

    let planner = SimplePlanner;
    let (logical, manifest) = planner.compile(&request).expect("compile should succeed");
    assert_eq!(manifest.expr_count, outputs.len(), "{manifest:?}");
    assert!(manifest.cse_hit_count >= 20, "{manifest:?}");

    let catalog = InputFieldCatalog::new(vec![
        "bar.open".to_string(),
        "bar.high".to_string(),
        "bar.low".to_string(),
        "bar.close".to_string(),
        "bar.volume".to_string(),
    ]);
    let physical = planner
        .bind(
            &logical,
            &Universe::new(universe.clone()),
            &catalog,
            AdvancePolicy::StrictAllReady,
        )
        .expect("bind should succeed");
    let mut engine = OnlineFactorEngine::default();
    engine.load(physical).expect("load should succeed");

    let mut offline_rows = Vec::new();
    let mut streaming = HashMap::new();
    for &ts in &ts_points {
        for (inst_idx, &instrument_slot) in universe.iter().enumerate() {
            let base = (inst_idx + 1) as f64;
            let t = ts as f64;
            let open = 80.0
                + 1.7 * base
                + t * (0.09 + 0.007 * base)
                + (t * (0.018 + 0.003 * base)).sin() * (0.9 + 0.08 * base);
            let close = open
                + base * 0.11
                + (t * (0.022 + 0.002 * base)).cos() * (0.45 + 0.04 * base)
                + (t * t) * (0.00002 * base);
            let high = open.max(close) + 0.22 + base * 0.012;
            let low = open.min(close) - 0.21 - base * 0.011;
            let volume = 1800.0
                + 70.0 * base
                + t * (2.6 + 0.18 * base)
                + (t * (0.015 + 0.002 * base)).cos() * 40.0;

            engine
                .on_event(&bar_event_ohlcv(
                    ts,
                    instrument_slot,
                    open,
                    high,
                    low,
                    close,
                    volume,
                ))
                .expect("bar event should succeed");
            offline_rows.push(OfflineInputRow {
                ts,
                instrument_slot,
                fields: BTreeMap::from([
                    ("open".to_string(), open),
                    ("high".to_string(), high),
                    ("low".to_string(), low),
                    ("close".to_string(), close),
                    ("volume".to_string(), volume),
                ]),
            });
        }
        let frame = engine.advance(ts).expect("advance should succeed");
        record_frame_results(&mut streaming, &frame, &outputs, &universe, ts);
    }

    let offline_all = run_polars_offline(&LegacyOfflinePayload {
        rows: offline_rows,
        expressions: vec![
            // Common derived series: vwap, returns, adv20.
            expr(
                "__vwap_oh",
                "elem_add",
                None,
                Some("open"),
                Some("high"),
                None,
                None,
            ),
            expr(
                "__vwap_lc",
                "elem_add",
                None,
                Some("low"),
                Some("close"),
                None,
                None,
            ),
            expr(
                "__vwap_num",
                "elem_add",
                None,
                Some("__vwap_oh"),
                Some("__vwap_lc"),
                None,
                None,
            ),
            expr(
                "__vwap",
                "elem_div",
                None,
                Some("__vwap_num"),
                Some("4"),
                None,
                None,
            ),
            expr(
                "__close_lag1",
                "ts_lag",
                Some("close"),
                None,
                None,
                None,
                Some(1),
            ),
            expr(
                "__ret_num",
                "ts_delta",
                Some("close"),
                None,
                None,
                None,
                Some(1),
            ),
            expr(
                "__ret_den",
                "elem_add",
                None,
                Some("__close_lag1"),
                Some("0.000001"),
                None,
                None,
            ),
            expr(
                "__returns",
                "elem_div",
                None,
                Some("__ret_num"),
                Some("__ret_den"),
                None,
                None,
            ),
            expr(
                "__adv20",
                "ts_mean",
                Some("volume"),
                None,
                None,
                Some(20),
                None,
            ),
            // alpha001
            expr(
                "__a001_std20",
                "ts_std",
                Some("__returns"),
                None,
                None,
                Some(20),
                None,
            ),
            expr(
                "__a001_cond",
                "elem_lt",
                None,
                Some("__returns"),
                Some("0"),
                None,
                None,
            ),
            expr(
                "__a001_pick",
                "elem_where",
                Some("__a001_cond"),
                Some("__a001_std20"),
                Some("close"),
                None,
                None,
            ),
            expr(
                "__a001_pow2",
                "elem_signed_power",
                None,
                Some("__a001_pick"),
                Some("2"),
                None,
                None,
            ),
            expr(
                "__a001_argmax5",
                "ts_argmax",
                Some("__a001_pow2"),
                None,
                None,
                Some(5),
                None,
            ),
            expr(
                "__a001_rank",
                "cs_rank",
                Some("__a001_argmax5"),
                None,
                None,
                None,
                None,
            ),
            expr(
                "alpha001",
                "elem_sub",
                None,
                Some("__a001_rank"),
                Some("0.5"),
                None,
                None,
            ),
            // alpha002
            expr(
                "__a002_logv",
                "elem_log",
                Some("volume"),
                None,
                None,
                None,
                None,
            ),
            expr(
                "__a002_dlogv2",
                "ts_delta",
                Some("__a002_logv"),
                None,
                None,
                None,
                Some(2),
            ),
            expr(
                "__a002_rank_l",
                "cs_rank",
                Some("__a002_dlogv2"),
                None,
                None,
                None,
                None,
            ),
            expr(
                "__a002_co",
                "elem_sub",
                None,
                Some("close"),
                Some("open"),
                None,
                None,
            ),
            expr(
                "__a002_co_div_o",
                "elem_div",
                None,
                Some("__a002_co"),
                Some("open"),
                None,
                None,
            ),
            expr(
                "__a002_rank_r",
                "cs_rank",
                Some("__a002_co_div_o"),
                None,
                None,
                None,
                None,
            ),
            expr(
                "__a002_corr",
                "ts_corr",
                None,
                Some("__a002_rank_l"),
                Some("__a002_rank_r"),
                Some(6),
                None,
            ),
            expr(
                "alpha002",
                "elem_mul",
                None,
                Some("-1"),
                Some("__a002_corr"),
                None,
                None,
            ),
            // alpha005
            expr(
                "__a005_close_vwap",
                "elem_sub",
                None,
                Some("close"),
                Some("__vwap"),
                None,
                None,
            ),
            expr(
                "__a005_rank_a",
                "cs_rank",
                Some("__a005_close_vwap"),
                None,
                None,
                None,
                None,
            ),
            expr(
                "__a005_abs_rank_a",
                "elem_abs",
                Some("__a005_rank_a"),
                None,
                None,
                None,
                None,
            ),
            expr(
                "__a005_vwap_mean10",
                "ts_mean",
                Some("__vwap"),
                None,
                None,
                Some(10),
                None,
            ),
            expr(
                "__a005_open_minus",
                "elem_sub",
                None,
                Some("open"),
                Some("__a005_vwap_mean10"),
                None,
                None,
            ),
            expr(
                "__a005_rank_b",
                "cs_rank",
                Some("__a005_open_minus"),
                None,
                None,
                None,
                None,
            ),
            expr(
                "__a005_mul",
                "elem_mul",
                None,
                Some("__a005_abs_rank_a"),
                Some("__a005_rank_b"),
                None,
                None,
            ),
            expr(
                "alpha005",
                "elem_mul",
                None,
                Some("-1"),
                Some("__a005_mul"),
                None,
                None,
            ),
            // alpha007
            expr(
                "__a007_cond",
                "elem_lt",
                None,
                Some("__adv20"),
                Some("volume"),
                None,
                None,
            ),
            expr(
                "__a007_dc7",
                "ts_delta",
                Some("close"),
                None,
                None,
                None,
                Some(7),
            ),
            expr(
                "__a007_sign",
                "elem_sign",
                Some("__a007_dc7"),
                None,
                None,
                None,
                None,
            ),
            expr(
                "__a007_abs",
                "elem_abs",
                Some("__a007_dc7"),
                None,
                None,
                None,
                None,
            ),
            expr(
                "__a007_rank60",
                "ts_rank",
                Some("__a007_abs"),
                None,
                None,
                Some(60),
                None,
            ),
            expr(
                "__a007_neg_sign",
                "elem_mul",
                None,
                Some("-1"),
                Some("__a007_sign"),
                None,
                None,
            ),
            expr(
                "__a007_then",
                "elem_mul",
                None,
                Some("__a007_neg_sign"),
                Some("__a007_rank60"),
                None,
                None,
            ),
            expr(
                "alpha007",
                "elem_where",
                Some("__a007_cond"),
                Some("__a007_then"),
                Some("-1"),
                None,
                None,
            ),
            // alpha008
            expr(
                "__a008_sum_open5",
                "ts_sum",
                Some("open"),
                None,
                None,
                Some(5),
                None,
            ),
            expr(
                "__a008_sum_ret5",
                "ts_sum",
                Some("__returns"),
                None,
                None,
                Some(5),
                None,
            ),
            expr(
                "__a008_prod",
                "elem_mul",
                None,
                Some("__a008_sum_open5"),
                Some("__a008_sum_ret5"),
                None,
                None,
            ),
            expr(
                "__a008_lag10",
                "ts_lag",
                Some("__a008_prod"),
                None,
                None,
                None,
                Some(10),
            ),
            expr(
                "__a008_diff",
                "elem_sub",
                None,
                Some("__a008_prod"),
                Some("__a008_lag10"),
                None,
                None,
            ),
            expr(
                "__a008_rank",
                "cs_rank",
                Some("__a008_diff"),
                None,
                None,
                None,
                None,
            ),
            expr(
                "alpha008",
                "elem_mul",
                None,
                Some("-1"),
                Some("__a008_rank"),
                None,
                None,
            ),
            // alpha009
            expr(
                "__x12",
                "ts_delta",
                Some("close"),
                None,
                None,
                None,
                Some(1),
            ),
            expr(
                "__a009_min5",
                "ts_min",
                Some("__x12"),
                None,
                None,
                Some(5),
                None,
            ),
            expr(
                "__a009_max5",
                "ts_max",
                Some("__x12"),
                None,
                None,
                Some(5),
                None,
            ),
            expr(
                "__a009_cond_up",
                "elem_gt",
                None,
                Some("__a009_min5"),
                Some("0"),
                None,
                None,
            ),
            expr(
                "__a009_cond_dn",
                "elem_lt",
                None,
                Some("__a009_max5"),
                Some("0"),
                None,
                None,
            ),
            expr(
                "__a009_neg",
                "elem_mul",
                None,
                Some("-1"),
                Some("__x12"),
                None,
                None,
            ),
            expr(
                "__a009_inner",
                "elem_where",
                Some("__a009_cond_dn"),
                Some("__x12"),
                Some("__a009_neg"),
                None,
                None,
            ),
            expr(
                "alpha009",
                "elem_where",
                Some("__a009_cond_up"),
                Some("__x12"),
                Some("__a009_inner"),
                None,
                None,
            ),
            // alpha010
            expr(
                "__a010_min4",
                "ts_min",
                Some("__x12"),
                None,
                None,
                Some(4),
                None,
            ),
            expr(
                "__a010_max4",
                "ts_max",
                Some("__x12"),
                None,
                None,
                Some(4),
                None,
            ),
            expr(
                "__a010_cond_up",
                "elem_gt",
                None,
                Some("__a010_min4"),
                Some("0"),
                None,
                None,
            ),
            expr(
                "__a010_cond_dn",
                "elem_lt",
                None,
                Some("__a010_max4"),
                Some("0"),
                None,
                None,
            ),
            expr(
                "__a010_neg",
                "elem_mul",
                None,
                Some("-1"),
                Some("__x12"),
                None,
                None,
            ),
            expr(
                "__a010_inner",
                "elem_where",
                Some("__a010_cond_dn"),
                Some("__x12"),
                Some("__a010_neg"),
                None,
                None,
            ),
            expr(
                "__a010_where",
                "elem_where",
                Some("__a010_cond_up"),
                Some("__x12"),
                Some("__a010_inner"),
                None,
                None,
            ),
            expr(
                "alpha010",
                "cs_rank",
                Some("__a010_where"),
                None,
                None,
                None,
                None,
            ),
            // alpha011
            expr(
                "__a011_close_vwap",
                "elem_sub",
                None,
                Some("close"),
                Some("__vwap"),
                None,
                None,
            ),
            expr(
                "__a011_neg",
                "elem_mul",
                None,
                Some("-1"),
                Some("__a011_close_vwap"),
                None,
                None,
            ),
            expr(
                "__a011_max3",
                "ts_max",
                Some("__a011_neg"),
                None,
                None,
                Some(3),
                None,
            ),
            expr(
                "__a011_min3",
                "ts_min",
                Some("__a011_neg"),
                None,
                None,
                Some(3),
                None,
            ),
            expr(
                "__a011_rank_max",
                "cs_rank",
                Some("__a011_max3"),
                None,
                None,
                None,
                None,
            ),
            expr(
                "__a011_rank_min",
                "cs_rank",
                Some("__a011_min3"),
                None,
                None,
                None,
                None,
            ),
            expr(
                "__a011_rank_sum",
                "elem_add",
                None,
                Some("__a011_rank_max"),
                Some("__a011_rank_min"),
                None,
                None,
            ),
            expr(
                "__a011_dv3",
                "ts_delta",
                Some("volume"),
                None,
                None,
                None,
                Some(3),
            ),
            expr(
                "__a011_rank_dv3",
                "cs_rank",
                Some("__a011_dv3"),
                None,
                None,
                None,
                None,
            ),
            expr(
                "alpha011",
                "elem_mul",
                None,
                Some("__a011_rank_sum"),
                Some("__a011_rank_dv3"),
                None,
                None,
            ),
            // alpha014
            expr(
                "__a014_dret3",
                "ts_delta",
                Some("__returns"),
                None,
                None,
                None,
                Some(3),
            ),
            expr(
                "__a014_rank",
                "cs_rank",
                Some("__a014_dret3"),
                None,
                None,
                None,
                None,
            ),
            expr(
                "__a014_corr",
                "ts_corr",
                None,
                Some("open"),
                Some("volume"),
                Some(10),
                None,
            ),
            expr(
                "__a014_mul",
                "elem_mul",
                None,
                Some("__a014_rank"),
                Some("__a014_corr"),
                None,
                None,
            ),
            expr(
                "alpha014",
                "elem_mul",
                None,
                Some("-1"),
                Some("__a014_mul"),
                None,
                None,
            ),
            // alpha017
            expr(
                "__a017_x28",
                "ts_delta",
                Some("__x12"),
                None,
                None,
                None,
                Some(1),
            ),
            expr(
                "__a017_rank_x28",
                "cs_rank",
                Some("__a017_x28"),
                None,
                None,
                None,
                None,
            ),
            expr(
                "__a017_ts_rank_close10",
                "ts_rank",
                Some("close"),
                None,
                None,
                Some(10),
                None,
            ),
            expr(
                "__a017_rank_x29",
                "cs_rank",
                Some("__a017_ts_rank_close10"),
                None,
                None,
                None,
                None,
            ),
            expr(
                "__a017_vol_adv",
                "elem_div",
                None,
                Some("volume"),
                Some("__adv20"),
                None,
                None,
            ),
            expr(
                "__a017_ts_rank_va5",
                "ts_rank",
                Some("__a017_vol_adv"),
                None,
                None,
                Some(5),
                None,
            ),
            expr(
                "__a017_rank_x30",
                "cs_rank",
                Some("__a017_ts_rank_va5"),
                None,
                None,
                None,
                None,
            ),
            expr(
                "__a017_mul_a",
                "elem_mul",
                None,
                Some("__a017_rank_x28"),
                Some("__a017_rank_x29"),
                None,
                None,
            ),
            expr(
                "__a017_mul_b",
                "elem_mul",
                None,
                Some("__a017_mul_a"),
                Some("__a017_rank_x30"),
                None,
                None,
            ),
            expr(
                "alpha017",
                "elem_mul",
                None,
                Some("-1"),
                Some("__a017_mul_b"),
                None,
                None,
            ),
            // alpha019
            expr(
                "__a019_sum_ret250",
                "ts_sum",
                Some("__returns"),
                None,
                None,
                Some(250),
                None,
            ),
            expr(
                "__a019_add1",
                "elem_add",
                None,
                Some("__a019_sum_ret250"),
                Some("1"),
                None,
                None,
            ),
            expr(
                "__a019_rank",
                "cs_rank",
                Some("__a019_add1"),
                None,
                None,
                None,
                None,
            ),
            expr(
                "__a019_x33",
                "elem_add",
                None,
                Some("__a019_rank"),
                Some("1"),
                None,
                None,
            ),
            expr(
                "__a019_lag7",
                "ts_lag",
                Some("close"),
                None,
                None,
                None,
                Some(7),
            ),
            expr(
                "__a019_add_close_dc7",
                "elem_add",
                None,
                Some("close"),
                Some("__a007_dc7"),
                None,
                None,
            ),
            expr(
                "__a019_sign_inner",
                "elem_sub",
                None,
                Some("__a019_add_close_dc7"),
                Some("__a019_lag7"),
                None,
                None,
            ),
            expr(
                "__a019_sign",
                "elem_sign",
                Some("__a019_sign_inner"),
                None,
                None,
                None,
                None,
            ),
            expr(
                "__a019_mul",
                "elem_mul",
                None,
                Some("__a019_x33"),
                Some("__a019_sign"),
                None,
                None,
            ),
            expr(
                "alpha019",
                "elem_mul",
                None,
                Some("-1"),
                Some("__a019_mul"),
                None,
                None,
            ),
        ],
    });

    let offline = retain_outputs(&offline_all, &outputs);
    let streaming = retain_from_ts(&streaming, 280);
    let offline = retain_from_ts(&offline, 280);

    assert_eq!(streaming.len(), offline.len(), "key count mismatch");
    for (key, lhs) in &streaming {
        let rhs = offline.get(key).expect("offline key missing");
        assert_close(*lhs, *rhs, key);
    }
}
